from typing import Protocol
from uuid import UUID

from auth.account import Account


class AccountRepository(Protocol):
    async def save(self, account: Account) -> None: ...

    async def find_by_email(self, email: str) -> Account | None: ...

    async def find_by_id(self, account_id: UUID) -> Account | None: ...

    async def lock_for_update(self, account_id: UUID) -> Account | None: ...

    async def transition_to_verified(self, account_id: UUID) -> bool: ...

    async def increment_failed_attempts(self, account_id: UUID) -> None: ...

    async def reset_failed_attempts(self, account_id: UUID) -> None: ...
