import asyncio
from datetime import UTC, datetime
from uuid import UUID, uuid4

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from access.auth.account_storage import SqlAlchemyAccountRepository
from auth.account import Account
from model.auth.account_model import AccountModel
from statements.arranged import arranged


class FailedAttemptConcurrencyStatements:
    """DSL for the atomic failed-attempt increment guard (scenario 5.3).

    Owns a session factory so each racing increment runs in its own independent
    AsyncSession/transaction against the same postgres -- a real race, not a
    same-session round-trip.
    """

    def __init__(self, session_factory: async_sessionmaker[AsyncSession]) -> None:
        self._session_factory = session_factory
        self.account_id: UUID | None = None
        self.bystander_account_id: UUID | None = None
        self.final_failed_attempt_count: int | None = None
        self.bystander_failed_attempt_count: int | None = None

    # Both ids are generated by the seeding step; every later step reads them
    # back. The properties make that ordering a checked precondition.
    @property
    def target_account_id(self) -> UUID:
        return arranged(self.account_id, "account_id")

    @property
    def untouched_account_id(self) -> UUID:
        return arranged(self.bystander_account_id, "bystander_account_id")

    def _new_verified_account(self, account_id):
        return Account.reconstitute(
            id=account_id,
            # Per-run-unique: uq_accounts_email would make a fixed literal collide
            # (ConflictException) on reruns against the persistent test postgres.
            email=f"fail-{uuid4()}@example.com",
            password_hash="hashed-password-value",
            created_at=datetime.now(UTC),
            is_verified=True,
        )

    async def insert_verified_account(self) -> None:
        self.account_id = account_id = uuid4()
        self.bystander_account_id = bystander_id = uuid4()
        # Bystander is the targeting guard: race_two_increments touches ONLY
        # account_id. A green whose UPDATE omits `WHERE id = :account_id` bumps
        # every row, so the bystander would read 2 and fail assert_bystander_untouched.
        target = self._new_verified_account(account_id)
        bystander = self._new_verified_account(bystander_id)
        async with self._session_factory() as session:
            repository = SqlAlchemyAccountRepository(session)
            await repository.save(target)
            await repository.save(bystander)
            await session.commit()

    async def _increment_in_own_session(self) -> None:
        async with self._session_factory() as session:
            await SqlAlchemyAccountRepository(session).increment_failed_attempts(
                self.target_account_id
            )
            await session.commit()

    async def race_two_increments(self) -> None:
        await asyncio.gather(
            self._increment_in_own_session(),
            self._increment_in_own_session(),
        )

    async def fetch_final_failed_attempt_count(self) -> None:
        async with self._session_factory() as session:
            model = await session.get(AccountModel, self.account_id)
            self.final_failed_attempt_count = model.failed_attempt_count if model else None
            bystander = await session.get(AccountModel, self.bystander_account_id)
            self.bystander_failed_attempt_count = (
                bystander.failed_attempt_count if bystander else None
            )

    def assert_final_count_is_two(self) -> None:
        # Load-bearing falsification guard: DB-side `SET count = count + 1`
        # serializes on the row lock and both increments land (final == 2). An
        # ORM load-then-save green (both racers read 0, both write 1) yields 1 and
        # fails here -- this assertion is what distinguishes atomic from
        # lost-update, exactly as scenario 5.3 requires.
        assert self.final_failed_attempt_count == 2, (
            f"expected final failed_attempt_count=2 (both atomic increments landed), "
            f"got {self.final_failed_attempt_count!r}"
        )

    def assert_bystander_untouched(self) -> None:
        # Targeting guard: race_two_increments incremented ONLY account_id. A green
        # UPDATE missing `WHERE id = :account_id` would bump every row, so the
        # bystander would read 2 here. Exact == 0 catches that lost WHERE, exactly
        # as assert_final_count_is_two catches a lost-update non-atomic increment.
        assert self.bystander_failed_attempt_count == 0, (
            f"expected bystander failed_attempt_count=0 (increment targeted only the "
            f"racing account), got {self.bystander_failed_attempt_count!r}"
        )
