"""The twelve names the analytics catalogue declares.

One domain-owned enumeration, per the story's AcceptanceCriteria ("All 12
catalogue names exist in one domain-owned enumeration"). Eight are emitted by
this story's code; the four subscription names are declared and silent, because
no pricing or subscription screen exists yet.

This is a plain tuple of constants, not a validating value object. Nothing in
scenario 1.1 refuses a name -- the catalogue-validating `EventName` (and the
narrower browser-origin subset the public route accepts) arrives with §2.1/§2.2,
the first scenarios that assert a refusal. What the tuple is needed for *now* is
the `analytics_events.event_name` CHECK constraint, which is generated by
iterating it rather than written as twelve literals: adding a thirteenth name
here without a migration then turns Infra §1.6 red in CI, where written-out
literals would stay green through the drift forever
(`decisions/analytics-ingest-shape-decision.md`).
"""

# Emitted by this story. The first three are browser-origin -- the only names the
# public ingest route accepts; the remaining five are server-emitted from the
# persisted transition they name.
SITE_VISITED = "SITE_VISITED"
REGISTRATION_STARTED = "REGISTRATION_STARTED"
EDITOR_OPENED = "EDITOR_OPENED"
REGISTRATION_COMPLETED = "REGISTRATION_COMPLETED"
LOGIN_SUCCESS = "LOGIN_SUCCESS"
GENERATION_STARTED = "GENERATION_STARTED"
GENERATION_COMPLETED = "GENERATION_COMPLETED"
DOCUMENT_SAVED = "DOCUMENT_SAVED"

# Declared, never emitted by this story: there are no pricing or subscription
# screens to emit them from. They are in the catalogue -- and so in the column's
# CHECK constraint -- so that the story that builds those screens adds an emitter
# rather than a migration on a populated table.
PRICING_OPENED = "PRICING_OPENED"
CHECKOUT_STARTED = "CHECKOUT_STARTED"
SUBSCRIPTION_ACTIVATED = "SUBSCRIPTION_ACTIVATED"
AUTO_RENEW_DISABLED = "AUTO_RENEW_DISABLED"

EVENT_NAMES = (
    SITE_VISITED,
    REGISTRATION_STARTED,
    EDITOR_OPENED,
    REGISTRATION_COMPLETED,
    LOGIN_SUCCESS,
    GENERATION_STARTED,
    GENERATION_COMPLETED,
    DOCUMENT_SAVED,
    PRICING_OPENED,
    CHECKOUT_STARTED,
    SUBSCRIPTION_ACTIVATED,
    AUTO_RENEW_DISABLED,
)
